{
 "title": "Test Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Загрузка CPU SQL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Трафик MCLAG SQL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=\"82.148.20.33:9182\",nic=\"Mellanox_ConnectX_3_Pro_Ethernet_Adapter\"}[5m])*8>0"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{instance=\"82.148.20.33:9182\",nic=\"Mellanox_ConnectX_3_Pro_Ethernet_Adapter__2\"}[5m])*8>0"
    }
   ]
  },
  {
   "title": "Node CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) without (cpu) * 100"
    }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}