global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'windows_exporter'
    file_sd_configs:
    - files:
      - ./sd_files/*_windows_exporter.yml
      refresh_interval: 1m

  - job_name: 'oxidized_exporter'
    static_configs:
      - targets:
        - oxidized.gktexnikapro.ru:5002

  - job_name: 'mikrotik-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.mikrotik-exporter'
      type: 'A'
      port: 9436

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
    - files:
      - ./sd_files/*_blackbox_icmp_exporter.yml
      refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mon_blackbox-icmp:9115
