devices:
  - name: Server_VPN
    address: 192.168.5.1
  - name: Adelia_Kut_MF/MTS
    address: 192.168.16.10
  - name: Adelia_Kut_T2
    address: 10.16.11.1
  - name: Kukmor_T2
    address: 192.168.16.12
  - name: Vasilevo_MF/T2
    address: 192.168.16.13
  - name: Dementeva_T2
    address: 192.168.14.14
  - name: Dzalil_T2_CHE
    address: 192.168.16.15
  - name: Gudovancevo_T2
    address: 192.168.16.16
  - name: Zalesny_T2
    address: 192.168.16.17
  - name: Zelenodolsk_MF/T2
    address: 192.168.16.18
  - name: Zorge_75_T2/MTS
    address: 192.168.16.19
  - name: Zorge_93_T2
    address: 192.168.16.20
  - name: Kolco_T2
    address: 192.168.16.22
  - name: Bavly
    address: 192.168.16.23
  - name: Leningradskaya_MF
    address: 192.168.16.25
  - name: Lomzhinskaya_MF/T2
    address: 192.168.16.26
  - name: Mavlutova_T2
    address: 192.168.16.27
  - name: Megga_Mebel_MTS
    address: 192.168.16.28
  - name: Menzelinsk_T2_CHE
    address: 192.168.16.29
  - name: Yamasheva_71_MTS
    address: 192.168.16.30
  - name: TC_Sitimoll_T2_CHE
    address: 192.168.16.31
  - name: TC_Kazan_Moll_T2
    address: 192.168.16.32
  - name: Osinovo_Bil/MF/MTS
    address: 192.168.16.33
  - name: Osinovo_T2
    address: 192.168.16.34
  - name: Politra_T2_CHE
    address: 192.168.16.35
  - name: Park_House_T2_Modul
    address: 192.168.16.36
  - name: Park_House_T2_Salon
    address: 192.168.16.37
  - name: KZN_Derbishki
    address: 192.168.16.38
  - name: Roddom_MF/T2
    address: 192.168.16.39
  - name: TC_Chelni_Hleb_MTS
    address: 192.168.16.40
  - name: Tandem_T2
    address: 192.168.16.41
  - name: TC_Kvartal_T2_CHE
    address: 192.168.16.42
  - name: Urussy_MTS/MF
    address: 192.168.16.43
  - name: KZN_Derbishki_MF
    address: 192.168.16.44
  - name: Fuchika_64_T2
    address: 192.168.16.45
  - name: Energetik_T2_CHE
    address: 192.168.16.46
  - name: Udino_MF_MTS
    address: 192.168.16.47
  - name: Yagodnaya_MF
    address: 192.168.16.49
  - name: Yamashevo_MF/T2
    address: 192.168.16.50
  - name: ZUM_T2
    address: 192.168.16.53
  - name: TC_MOKI_MTS_MF
    address: 192.168.15.54
  - name: Arsk_T2
    address: 192.168.16.56
  - name: TC_Omega_CHE
    address: 192.168.16.57
  - name: TC_MOKI_T2
    address: 192.168.16.59
  - name: Zorge_66_T2
    address: 192.168.16.60
  - name: Visokaya_gora_MTS
    address: 192.168.16.61
  - name: KRV_office
    address: 192.168.43.2
  - name: JemMol_T2_Kir
    address: 192.168.43.10
  - name: TC_Leto_T2_Kir
    address: 192.168.43.11
  - name: TC_Maximum_T2_Kir
    address: 192.168.43.12
  - name: PR_Oktabr_16_Kir
    address: 192.168.43.13
  - name: Lepse_T2_kir
    address: 192.168.43.14
  - name: Upita_T2_Kir
    address: 192.168.43.15
  - name: Kirovo_Chepetsk_60_let
    address: 192.168.43.16
  - name: Kirovo_Chepetsk_Mira_74
    address: 192.168.43.17
  - name: Vorovskogo_77_KIR
    address: 192.168.43.18
  - name: Shorsa_95_T2_Kir
    address: 192.168.43.19
  - name: TC_Rossia_Kir
    address: 192.168.43.20
  - name: Viat_Pol_Gagarina_11_T2
    address: 192.168.43.21
  - name: JemMol_Xiaomi_kir
    address: 192.168.43.22
  - name: KRV_Luganskaia_53_T2_TC_Maxi
    address: 192.168.43.23
  - name: JemMol_Xiaomi_kir_Sklad
    address: 192.168.43.24
  - name: Office_Perm
    address: 192.168.59.2
  - name: PRM_Krisanova_19_T2
    address: 192.168.59.10
  - name: PRM_Popova_61
    address: 192.168.59.11
  - name: PRM_Kosmonavtov_256
    address: 192.168.59.12
  - name: PRM_Vetluzhskaia
    address: 192.168.59.13
  - name: PRM_Ushakova
    address: 192.168.59.14
  - name: PRM_PR_Parkovi
    address: 192.168.59.15
  - name: PRM_Chaikovski_Marksa_T2
    address: 192.168.59.16
  - name: PRM_Berez_Piatiletki_87
    address: 192.168.59.17
  - name: PRM_Berez_Piatiletki_41_TC_CUM
    address: 192.168.59.18
  - name: PRM_Berezn_Ubileinaia_28
    address: 192.168.59.19
  - name: PRM_Berezn_Mira_82_Semia
    address: 192.168.59.20
  - name: PRM_Solik_Sevrnaia_48_TC_Bismark_Avenu
    address: 192.168.59.21
  - name: PRM_Solik_Lenina_36b_TC_Bismark_Plaza
    address: 192.168.59.22
  - name: PRM_Solik_Pobedy_117_TC_CUM
    address: 192.168.59.23
  - name: PRM_Chaikovski_Marksa_XIAOMI
    address: 192.168.59.25

features:
  conntrack: true
  dhcp: true
  dhcpl: true
  wlansta: true
  wlanif: true
  ipsec: true
  lte: true
  netwatch: true
  poe: true
  monitor: true
  health: true
  devices: true
